### ISSUE TITLE
Module Not Found "styled-components"

### ISSUE THREAD

**Issue by mass-gueye** [gjmolter/revo-calendar#10]
after yarn start it says:

./node_modules/revo-calendar/dist/index.js
Module not found: Can't resolve 'styled-components' in 'C:\Users\mass\OneDrive\Bureau\demo-calendar\node_modules\revo-calendar\dist'

**Comment by NazrulChowdhury** [comment]
I did a npm i styled-components. That solved the issue.

**Comment by gjmolter** [comment]
The `styled-components` module has been added to the package dependencies, so this error shouldn't be happening anymore. 👍
