### ISSUE TITLE
Add event btn not working

### ISSUE THREAD

**Issue by ShyrenMore** [gjmolter/revo-calendar#4]
Hello, I recently installed this package via npm and added the ```<RevoCalendar />``` with only event props, when I tried adding an event, a modal didn't show up, do I need to create my own state variables and functions?
I am a beginner at this 😅
sorry for the inconvenience

I did go through the readme and came across the addEvent prop, but I didn't understand ```date => {}```, is that an anonymous/inline function?
inside the object do we have to append it this way?
```
<RevoCalendar 
  data => {
   day: day,
   month: month,
   year: year,
  }
/>
```

**Comment by gjmolter** [comment]
Hey! It does work, but it won't bring up a modal. I made it so you could use any interface you might need for event adding. The addEvent prop takes a function, in which you can open a modal or do any other thing you want. The `date` parameter will contain the current selected day on the calendar, so you can add the event to the correct day. 

The piece of code you've posted won't work. For it to work correctly, it will have to look something like this:

```
<RevoCalendar 
  events={eventList} 
  addEvent={(date) => {
    showModalWithInputs()
    //When user finishes inputing the event data, append the new event to the eventList array and close the modal
   }}
 />
```

Take a look at my exemple code, I guess it will become clearer.

**Comment by ShyrenMore** [comment]
Thanks!!
your example did help me to understand it
Loved this package!
