### ISSUE TITLE
text-overflow

### ISSUE THREAD

**Issue by ShyrenMore** [gjmolter/revo-calendar#5]
![image](https://user-images.githubusercontent.com/56788568/117562323-bfe8a580-b0bb-11eb-9779-2c964922822a.png)

Hello, I observed the text-overflow when the user inputs the text value, however when it's hardcoded then it does not overflow like the below example: 

![image](https://user-images.githubusercontent.com/56788568/117562358-03431400-b0bc-11eb-80ff-2b4b3e405e43.png)
code for the eg
```
const [eventList, setEventList] = useState([
    {
    name: 'Buyout',
    date: +new Date(),
    allday: true,
      extra: {
      text: 'ooo some more text i wonder how many values it can hold hmm quite a few I must say, insert a few more to see the limit'
    }
    },
    
  ])

```

I don't know the root cause of this issue

**Comment by gjmolter** [comment]
Hey! Thanks for letting me know about this. I will investigate and come up with a fix in the next few days.

**Comment by gjmolter** [comment]
It has been fixed in the latest update, hope it will solve it for you!

**Comment by ShyrenMore** [comment]
Great!!, could you please tell it in short how did you do it? cause I am facing the same issue in another one of my own projects, i.e the span tag doesn't occupy the entire content

![image](https://user-images.githubusercontent.com/56788568/120058368-f769c280-c067-11eb-8c8f-27699e9e8e56.png)

**Comment by gjmolter** [comment]
Hey! I've just added the CSS `word-break: break-word;` property to the element. But I guess you're facing a different kind of issue there
