### ISSUE TITLE
dateSelected in revo-calendar gives wrong month

### ISSUE THREAD

**Issue by tmax-siva** [gjmolter/revo-calendar#8]
Dear @gjmolter

I am trying to **get the selected date on the calendar**, but when I try to achieve this I am not getting the correct month. When **I select 12/July/2021**, it **gives me 12/June/2021**. It is always giving me **Selected Month - 1**

```
<RevoCalendar
  events={eventList}
  date={new Date()}
  timeFormat24={true}
  showDetailToggler={false}
  showSidebarToggler={false}
  dateSelected={(date: Date) => {
    console.log(date);
    alert(date["day"]+"/"+date["month"]+"/"+date["year"]);
  }}
/>
```
this is the code I've used to achieve the functionality.

Correct me if I missed out on anything.

Thanks in Advance.

**Comment by gjmolter** [comment]
Hey! I guess that is just how the Date object works in JS. While the day starts at 1, the month always starts at zero. So **Jan** is 0, **Feb** is 1, etc...

Take a look here, it may help: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth
