### ISSUE TITLE
How can we specify Date Range

### ISSUE THREAD

**Issue by tmax-siva** [gjmolter/revo-calendar#9]
Hi @gjmolter 
What is the step to give Date range, I wanted to highlight a date, (I,e., Start date = 13/July/2021 and End date = 16/July/2021) in this case I wanted to mark the date with an indicator (13, 14, 15, 16).

I tried and Failed with this method of doing.
{"allDay":true,"date":[""+moment(items[i].EventDate).toISOString()+"",""+moment(items[i].EndDate).toISOString()+""]}

How we can achieve this?

Thank you

**Comment by gjmolter** [comment]
Unfortunately it doesn't yet have the range feature. I am planning on adding it when I have some extra time. For now, the `date` property can only take a single timestamp.
